services:
  spyapp:
    image: benjaminderprogrammierer/spyapp:latest
    container_name: spyapp
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_CONNECTION_STRING: postgresql://${DB_USER:-postgres}:${DB_PASSWORD:-postgres}@db:5432/${DB_NAME:-spyapp}
      PORT: ${PORT:-3000}
      SESSION_SECRET: ${SESSION_SECRET}
      CLIENT_URL: http://localhost:${CLIENT_PORT:-3000}/,${CLIENT_URL}
    ports:
      - ${PORT:-3000}:${PORT:-3000}
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:18-alpine
    container_name: spyapp-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-spyapp}
    volumes:
      - spyapp_data:/var/lib/postgresql
      - type: bind
        source: ./wordlist.json
        target: /app/data/wordlist.json
    healthcheck:
      test: [CMD-SHELL, pg_isready -U postgres]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  spyapp_data:
